# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='msg.proto',
  package='simpleGRpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tmsg.proto\x12\nsimpleGRpc\"\x9b\x01\n\nRpcRequest\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x11\n\tparent_id\x18\x03 \x01(\t\x12\x13\n\x0btrace_level\x18\x04 \x01(\x05\x12\x14\n\x0cservice_name\x18\x05 \x01(\t\x12\x11\n\tpara_json\x18\x06 \x01(\t\x12\x16\n\x0ehas_para_bytes\x18\x07 \x01(\x08\x12\x12\n\npara_bytes\x18\x08 \x01(\x0c\"\xa2\x01\n\x0bRpcResponse\x12\x13\n\x0breturn_json\x18\x01 \x01(\t\x12\x18\n\x10has_return_bytes\x18\x02 \x01(\x08\x12\x14\n\x0creturn_bytes\x18\x03 \x01(\x0c\x12\x11\n\tcall_code\x18\x04 \x01(\t\x12\x10\n\x08\x63\x61ll_msg\x18\x05 \x01(\t\x12\x12\n\ncall_error\x18\x06 \x01(\t\x12\x15\n\rcall_msg_para\x18\x07 \x01(\t2\xd0\x02\n\x11SimpleGRpcService\x12\x43\n\x0eGRpcCallSimple\x12\x16.simpleGRpc.RpcRequest\x1a\x17.simpleGRpc.RpcResponse\"\x00\x12O\n\x18GRpcCallClientSideStream\x12\x16.simpleGRpc.RpcRequest\x1a\x17.simpleGRpc.RpcResponse\"\x00(\x01\x12O\n\x18GRpcCallServerSideStream\x12\x16.simpleGRpc.RpcRequest\x1a\x17.simpleGRpc.RpcResponse\"\x00\x30\x01\x12T\n\x1bGRpcCallBidirectionalStream\x12\x16.simpleGRpc.RpcRequest\x1a\x17.simpleGRpc.RpcResponse\"\x00(\x01\x30\x01\x62\x06proto3')
)




_RPCREQUEST = _descriptor.Descriptor(
  name='RpcRequest',
  full_name='simpleGRpc.RpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trace_id', full_name='simpleGRpc.RpcRequest.trace_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='simpleGRpc.RpcRequest.parent_id', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trace_level', full_name='simpleGRpc.RpcRequest.trace_level', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_name', full_name='simpleGRpc.RpcRequest.service_name', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='para_json', full_name='simpleGRpc.RpcRequest.para_json', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_para_bytes', full_name='simpleGRpc.RpcRequest.has_para_bytes', index=5,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='para_bytes', full_name='simpleGRpc.RpcRequest.para_bytes', index=6,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=181,
)


_RPCRESPONSE = _descriptor.Descriptor(
  name='RpcResponse',
  full_name='simpleGRpc.RpcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='return_json', full_name='simpleGRpc.RpcResponse.return_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_return_bytes', full_name='simpleGRpc.RpcResponse.has_return_bytes', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_bytes', full_name='simpleGRpc.RpcResponse.return_bytes', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='call_code', full_name='simpleGRpc.RpcResponse.call_code', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='call_msg', full_name='simpleGRpc.RpcResponse.call_msg', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='call_error', full_name='simpleGRpc.RpcResponse.call_error', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='call_msg_para', full_name='simpleGRpc.RpcResponse.call_msg_para', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=346,
)

DESCRIPTOR.message_types_by_name['RpcRequest'] = _RPCREQUEST
DESCRIPTOR.message_types_by_name['RpcResponse'] = _RPCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RpcRequest = _reflection.GeneratedProtocolMessageType('RpcRequest', (_message.Message,), dict(
  DESCRIPTOR = _RPCREQUEST,
  __module__ = 'msg_pb2'
  # @@protoc_insertion_point(class_scope:simpleGRpc.RpcRequest)
  ))
_sym_db.RegisterMessage(RpcRequest)

RpcResponse = _reflection.GeneratedProtocolMessageType('RpcResponse', (_message.Message,), dict(
  DESCRIPTOR = _RPCRESPONSE,
  __module__ = 'msg_pb2'
  # @@protoc_insertion_point(class_scope:simpleGRpc.RpcResponse)
  ))
_sym_db.RegisterMessage(RpcResponse)



_SIMPLEGRPCSERVICE = _descriptor.ServiceDescriptor(
  name='SimpleGRpcService',
  full_name='simpleGRpc.SimpleGRpcService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=349,
  serialized_end=685,
  methods=[
  _descriptor.MethodDescriptor(
    name='GRpcCallSimple',
    full_name='simpleGRpc.SimpleGRpcService.GRpcCallSimple',
    index=0,
    containing_service=None,
    input_type=_RPCREQUEST,
    output_type=_RPCRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GRpcCallClientSideStream',
    full_name='simpleGRpc.SimpleGRpcService.GRpcCallClientSideStream',
    index=1,
    containing_service=None,
    input_type=_RPCREQUEST,
    output_type=_RPCRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GRpcCallServerSideStream',
    full_name='simpleGRpc.SimpleGRpcService.GRpcCallServerSideStream',
    index=2,
    containing_service=None,
    input_type=_RPCREQUEST,
    output_type=_RPCRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GRpcCallBidirectionalStream',
    full_name='simpleGRpc.SimpleGRpcService.GRpcCallBidirectionalStream',
    index=3,
    containing_service=None,
    input_type=_RPCREQUEST,
    output_type=_RPCRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMPLEGRPCSERVICE)

DESCRIPTOR.services_by_name['SimpleGRpcService'] = _SIMPLEGRPCSERVICE

# @@protoc_insertion_point(module_scope)
